import pytest
from unitconversion import generate_sentances_fractions


@pytest.mark.parametrize(
    "test_input, expected",
    [
        (
            [0.1, "et_kk_nf", "núll komma einn"],
            [
                [0.1, "et_kk_nf", "Hvað er núll komma einn millimetri mörg fet?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millimetri margar tommur?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millimetri margar mílur?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn millimetri margir sentimetrar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millimetri margir metrar?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn millimetri margir kílómetrar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn sentimetri mörg fet?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn sentimetri margar tommur?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn sentimetri margar mílur?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn sentimetri margir millimetrar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn sentimetri margir metrar?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn sentimetri margir kílómetrar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn metri mörg fet?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn metri margar tommur?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn metri margar mílur?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn metri margir millimetrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn metri margir sentimetrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn metri margir kílómetrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn kílómetri mörg fet?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn kílómetri margar tommur?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn kílómetri margar mílur?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn kílómetri margir millimetrar?",
                ],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn kílómetri margir sentimetrar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn kílómetri margir metrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri margir millilítrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri margir desilítrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri mörg grömm?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri mörg kílógrömm?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri mörg pund?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri margir bollar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri margar únsur?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri margar matskeiðar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn lítri margir pelar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn desilítri margir lítrar?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn desilítri margir millilítrar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn desilítri mörg grömm?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn desilítri mörg kílógrömm?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn desilítri mörg pund?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn desilítri margir bollar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn desilítri margar únsur?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn desilítri margar matskeiðar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn desilítri margir pelar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millilítri margir lítrar?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn millilítri margir desilítrar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millilítri mörg grömm?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millilítri mörg kílógrömm?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millilítri mörg pund?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millilítri margir bollar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millilítri margar únsur?"],
                [
                    0.1,
                    "et_kk_nf",
                    "Hvað er núll komma einn millilítri margar matskeiðar?",
                ],
                [0.1, "et_kk_nf", "Hvað er núll komma einn millilítri margir pelar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli margir lítrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli margir millilítrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli margir desilítrar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli mörg grömm?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli mörg kílógrömm?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli mörg pund?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli margir bollar?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli margar únsur?"],
                [0.1, "et_kk_nf", "Hvað er núll komma einn peli margar matskeiðar?"],
            ],
        ),
        (
            [1.1, "et_kk_þgf", "einum komma einum"],
            [
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu mörg fet eru í einum komma einum millimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margar tommur eru í einum komma einum millimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margar mílur eru í einum komma einum millimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir sentimetrar eru í einum komma einum millimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir metrar eru í einum komma einum millimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir kílómetrar eru í einum komma einum millimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu mörg fet eru í einum komma einum sentimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margar tommur eru í einum komma einum sentimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margar mílur eru í einum komma einum sentimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir millimetrar eru í einum komma einum sentimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir metrar eru í einum komma einum sentimetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir kílómetrar eru í einum komma einum sentimetra?",
                ],
                [1.1, "et_kk_þgf", "Hversu mörg fet eru í einum komma einum metra?"],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margar tommur eru í einum komma einum metra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margar mílur eru í einum komma einum metra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir millimetrar eru í einum komma einum metra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir sentimetrar eru í einum komma einum metra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir kílómetrar eru í einum komma einum metra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu mörg fet eru í einum komma einum kílómetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margar tommur eru í einum komma einum kílómetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margar mílur eru í einum komma einum kílómetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir millimetrar eru í einum komma einum kílómetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir sentimetrar eru í einum komma einum kílómetra?",
                ],
                [
                    1.1,
                    "et_kk_þgf",
                    "Hversu margir metrar eru í einum komma einum kílómetra?",
                ],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum millimetra í fet"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum millimetra í tommur"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum millimetra í mílur"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum millimetra í sentimetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum millimetra í metra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum millimetra í kílómetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum sentimetra í fet"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum sentimetra í tommur"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum sentimetra í mílur"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum sentimetra í millimetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum sentimetra í metra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum sentimetra í kílómetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum metra í fet"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum metra í tommur"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum metra í mílur"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum metra í millimetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum metra í sentimetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum metra í kílómetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum kílómetra í fet"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum kílómetra í tommur"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum kílómetra í mílur"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum kílómetra í millimetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum kílómetra í sentimetra"],
                [1.1, "et_kk_þgf", "Breyttu einum komma einum kílómetra í metra"],
            ],
        ),
        (
            [1.2, "ft_kvk_þgf", "einum komma tveimur"],
            [
                [1.2, "ft_kvk_þgf", "Hversu mörg fet eru í einum komma tveimur mílum?"],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margar tommur eru í einum komma tveimur mílum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margir millimetrar eru í einum komma tveimur mílum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margir sentimetrar eru í einum komma tveimur mílum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margir metrar eru í einum komma tveimur mílum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margir kílómetrar eru í einum komma tveimur mílum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu mörg fet eru í einum komma tveimur tommum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margar mílur eru í einum komma tveimur tommum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margir millimetrar eru í einum komma tveimur tommum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margir sentimetrar eru í einum komma tveimur tommum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margir metrar eru í einum komma tveimur tommum?",
                ],
                [
                    1.2,
                    "ft_kvk_þgf",
                    "Hversu margir kílómetrar eru í einum komma tveimur tommum?",
                ],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur mílum í fet"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur mílum í tommur"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur mílum í millimetra"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur mílum í sentimetra"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur mílum í metra"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur mílum í kílómetra"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur tommum í fet"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur tommum í mílur"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur tommum í millimetra"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur tommum í sentimetra"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur tommum í metra"],
                [1.2, "ft_kvk_þgf", "Breyttu einum komma tveimur tommum í kílómetra"],
            ],
        ),
        (
            [1.3, "ft_kk_nf", "einn komma þrír"],
            [
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír millimetrar mörg fet?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millimetrar margar tommur?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír millimetrar margar mílur?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millimetrar margir sentimetrar?",
                ],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millimetrar margir metrar?",
                ],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millimetrar margir kílómetrar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír sentimetrar mörg fet?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír sentimetrar margar tommur?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír sentimetrar margar mílur?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír sentimetrar margir millimetrar?",
                ],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír sentimetrar margir metrar?",
                ],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír sentimetrar margir kílómetrar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír metrar mörg fet?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír metrar margar tommur?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír metrar margar mílur?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír metrar margir millimetrar?",
                ],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír metrar margir sentimetrar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír metrar margir kílómetrar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír kílómetrar mörg fet?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír kílómetrar margar tommur?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír kílómetrar margar mílur?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír kílómetrar margir millimetrar?",
                ],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír kílómetrar margir sentimetrar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír kílómetrar margir metrar?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír lítrar margir millilítrar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír lítrar margir desilítrar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír lítrar mörg grömm?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír lítrar mörg kílógrömm?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír lítrar mörg pund?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír lítrar margir bollar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír lítrar margar únsur?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír lítrar margar matskeiðar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír lítrar margir pelar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír desilítrar margir lítrar?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír desilítrar margir millilítrar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír desilítrar mörg grömm?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír desilítrar mörg kílógrömm?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír desilítrar mörg pund?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír desilítrar margir bollar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír desilítrar margar únsur?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír desilítrar margar matskeiðar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír desilítrar margir pelar?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millilítrar margir lítrar?",
                ],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millilítrar margir desilítrar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír millilítrar mörg grömm?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millilítrar mörg kílógrömm?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír millilítrar mörg pund?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millilítrar margir bollar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír millilítrar margar únsur?"],
                [
                    1.3,
                    "ft_kk_nf",
                    "Hvað eru einn komma þrír millilítrar margar matskeiðar?",
                ],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír millilítrar margir pelar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar margir lítrar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar margir millilítrar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar margir desilítrar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar mörg grömm?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar mörg kílógrömm?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar mörg pund?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar margir bollar?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar margar únsur?"],
                [1.3, "ft_kk_nf", "Hvað eru einn komma þrír pelar margar matskeiðar?"],
            ],
        ),
        (
            [1.4, "ft_kk_nf", "einn komma fjórir"],
            [
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir millimetrar mörg fet?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millimetrar margar tommur?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millimetrar margar mílur?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millimetrar margir sentimetrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millimetrar margir metrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millimetrar margir kílómetrar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir sentimetrar mörg fet?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir sentimetrar margar tommur?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir sentimetrar margar mílur?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir sentimetrar margir millimetrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir sentimetrar margir metrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir sentimetrar margir kílómetrar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir metrar mörg fet?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir metrar margar tommur?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir metrar margar mílur?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir metrar margir millimetrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir metrar margir sentimetrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir metrar margir kílómetrar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir kílómetrar mörg fet?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir kílómetrar margar tommur?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir kílómetrar margar mílur?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir kílómetrar margir millimetrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir kílómetrar margir sentimetrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir kílómetrar margir metrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir lítrar margir millilítrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir lítrar margir desilítrar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir lítrar mörg grömm?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir lítrar mörg kílógrömm?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir lítrar mörg pund?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir lítrar margir bollar?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir lítrar margar únsur?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir lítrar margar matskeiðar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir lítrar margir pelar?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir desilítrar margir lítrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir desilítrar margir millilítrar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir desilítrar mörg grömm?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir desilítrar mörg kílógrömm?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir desilítrar mörg pund?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir desilítrar margir bollar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir desilítrar margar únsur?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir desilítrar margar matskeiðar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir desilítrar margir pelar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millilítrar margir lítrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millilítrar margir desilítrar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir millilítrar mörg grömm?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millilítrar mörg kílógrömm?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir millilítrar mörg pund?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millilítrar margir bollar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millilítrar margar únsur?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millilítrar margar matskeiðar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir millilítrar margir pelar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir pelar margir lítrar?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir pelar margir millilítrar?",
                ],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir pelar margir desilítrar?",
                ],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir pelar mörg grömm?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir pelar mörg kílógrömm?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir pelar mörg pund?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir pelar margir bollar?"],
                [1.4, "ft_kk_nf", "Hvað eru einn komma fjórir pelar margar únsur?"],
                [
                    1.4,
                    "ft_kk_nf",
                    "Hvað eru einn komma fjórir pelar margar matskeiðar?",
                ],
            ],
        ),(
            [1.9, "ft_hk_nf", "eitt komma níu"],
            [
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm margir lítrar?"],
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm margir millilítrar?"],
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm margir desilítrar?"],
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm mörg kílógrömm?"],
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm mörg pund?"],
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm margir bollar?"],
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm margar únsur?"],
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm margar matskeiðar?"],
                [1.9, "ft_hk_nf", "Hvað eru eitt komma níu grömm margir pelar?"],
            ],
        ),
    ],
)
def test_fractions(test_input, expected):
    assert generate_sentances_fractions(*test_input) == expected
