import pytest
from unitconversion import generate_sentances_integers


@pytest.mark.parametrize(
    "test_input, expected",
    [
        (
            [1, "et_kk_nf", "einn"],
            [
                [1, "et_kk_nf", "Hvað er einn millimetri mörg fet?"],
                [1, "et_kk_nf", "Hvað er einn millimetri margar tommur?"],
                [1, "et_kk_nf", "Hvað er einn millimetri margar mílur?"],
                [1, "et_kk_nf", "Hvað er einn millimetri margir sentimetrar?"],
                [1, "et_kk_nf", "Hvað er einn millimetri margir metrar?"],
                [1, "et_kk_nf", "Hvað er einn millimetri margir kílómetrar?"],
                [1, "et_kk_nf", "Hvað er einn sentimetri mörg fet?"],
                [1, "et_kk_nf", "Hvað er einn sentimetri margar tommur?"],
                [1, "et_kk_nf", "Hvað er einn sentimetri margar mílur?"],
                [1, "et_kk_nf", "Hvað er einn sentimetri margir millimetrar?"],
                [1, "et_kk_nf", "Hvað er einn sentimetri margir metrar?"],
                [1, "et_kk_nf", "Hvað er einn sentimetri margir kílómetrar?"],
                [1, "et_kk_nf", "Hvað er einn metri mörg fet?"],
                [1, "et_kk_nf", "Hvað er einn metri margar tommur?"],
                [1, "et_kk_nf", "Hvað er einn metri margar mílur?"],
                [1, "et_kk_nf", "Hvað er einn metri margir millimetrar?"],
                [1, "et_kk_nf", "Hvað er einn metri margir sentimetrar?"],
                [1, "et_kk_nf", "Hvað er einn metri margir kílómetrar?"],
                [1, "et_kk_nf", "Hvað er einn kílómetri mörg fet?"],
                [1, "et_kk_nf", "Hvað er einn kílómetri margar tommur?"],
                [1, "et_kk_nf", "Hvað er einn kílómetri margar mílur?"],
                [1, "et_kk_nf", "Hvað er einn kílómetri margir millimetrar?"],
                [1, "et_kk_nf", "Hvað er einn kílómetri margir sentimetrar?"],
                [1, "et_kk_nf", "Hvað er einn kílómetri margir metrar?"],
                [1, "et_kk_nf", "Hvað er einn lítri margir millilítrar?"],
                [1, "et_kk_nf", "Hvað er einn lítri margir desilítrar?"],
                [1, "et_kk_nf", "Hvað er einn lítri mörg grömm?"],
                [1, "et_kk_nf", "Hvað er einn lítri mörg kílógrömm?"],
                [1, "et_kk_nf", "Hvað er einn lítri mörg pund?"],
                [1, "et_kk_nf", "Hvað er einn lítri margir bollar?"],
                [1, "et_kk_nf", "Hvað er einn lítri margar únsur?"],
                [1, "et_kk_nf", "Hvað er einn lítri margar matskeiðar?"],
                [1, "et_kk_nf", "Hvað er einn lítri margir pelar?"],
                [1, "et_kk_nf", "Hvað er einn desilítri margir lítrar?"],
                [1, "et_kk_nf", "Hvað er einn desilítri margir millilítrar?"],
                [1, "et_kk_nf", "Hvað er einn desilítri mörg grömm?"],
                [1, "et_kk_nf", "Hvað er einn desilítri mörg kílógrömm?"],
                [1, "et_kk_nf", "Hvað er einn desilítri mörg pund?"],
                [1, "et_kk_nf", "Hvað er einn desilítri margir bollar?"],
                [1, "et_kk_nf", "Hvað er einn desilítri margar únsur?"],
                [1, "et_kk_nf", "Hvað er einn desilítri margar matskeiðar?"],
                [1, "et_kk_nf", "Hvað er einn desilítri margir pelar?"],
                [1, "et_kk_nf", "Hvað er einn millilítri margir lítrar?"],
                [1, "et_kk_nf", "Hvað er einn millilítri margir desilítrar?"],
                [1, "et_kk_nf", "Hvað er einn millilítri mörg grömm?"],
                [1, "et_kk_nf", "Hvað er einn millilítri mörg kílógrömm?"],
                [1, "et_kk_nf", "Hvað er einn millilítri mörg pund?"],
                [1, "et_kk_nf", "Hvað er einn millilítri margir bollar?"],
                [1, "et_kk_nf", "Hvað er einn millilítri margar únsur?"],
                [1, "et_kk_nf", "Hvað er einn millilítri margar matskeiðar?"],
                [1, "et_kk_nf", "Hvað er einn millilítri margir pelar?"],
                [1, "et_kk_nf", "Hvað er einn peli margir lítrar?"],
                [1, "et_kk_nf", "Hvað er einn peli margir millilítrar?"],
                [1, "et_kk_nf", "Hvað er einn peli margir desilítrar?"],
                [1, "et_kk_nf", "Hvað er einn peli mörg grömm?"],
                [1, "et_kk_nf", "Hvað er einn peli mörg kílógrömm?"],
                [1, "et_kk_nf", "Hvað er einn peli mörg pund?"],
                [1, "et_kk_nf", "Hvað er einn peli margir bollar?"],
                [1, "et_kk_nf", "Hvað er einn peli margar únsur?"],
                [1, "et_kk_nf", "Hvað er einn peli margar matskeiðar?"],
            ],
        ),
        (
            [2, "ft_kvk_þgf", "tveim"],
            [
                [2, "ft_kvk_þgf", "Hversu mörg fet eru í tveim mílum?"],
                [2, "ft_kvk_þgf", "Hversu margar tommur eru í tveim mílum?"],
                [2, "ft_kvk_þgf", "Hversu margir millimetrar eru í tveim mílum?"],
                [2, "ft_kvk_þgf", "Hversu margir sentimetrar eru í tveim mílum?"],
                [2, "ft_kvk_þgf", "Hversu margir metrar eru í tveim mílum?"],
                [2, "ft_kvk_þgf", "Hversu margir kílómetrar eru í tveim mílum?"],
                [2, "ft_kvk_þgf", "Hversu mörg fet eru í tveim tommum?"],
                [2, "ft_kvk_þgf", "Hversu margar mílur eru í tveim tommum?"],
                [2, "ft_kvk_þgf", "Hversu margir millimetrar eru í tveim tommum?"],
                [2, "ft_kvk_þgf", "Hversu margir sentimetrar eru í tveim tommum?"],
                [2, "ft_kvk_þgf", "Hversu margir metrar eru í tveim tommum?"],
                [2, "ft_kvk_þgf", "Hversu margir kílómetrar eru í tveim tommum?"],
                [2, "ft_kvk_þgf", "Breyttu tveim mílum í fet"],
                [2, "ft_kvk_þgf", "Breyttu tveim mílum í tommur"],
                [2, "ft_kvk_þgf", "Breyttu tveim mílum í millimetra"],
                [2, "ft_kvk_þgf", "Breyttu tveim mílum í sentimetra"],
                [2, "ft_kvk_þgf", "Breyttu tveim mílum í metra"],
                [2, "ft_kvk_þgf", "Breyttu tveim mílum í kílómetra"],
                [2, "ft_kvk_þgf", "Breyttu tveim tommum í fet"],
                [2, "ft_kvk_þgf", "Breyttu tveim tommum í mílur"],
                [2, "ft_kvk_þgf", "Breyttu tveim tommum í millimetra"],
                [2, "ft_kvk_þgf", "Breyttu tveim tommum í sentimetra"],
                [2, "ft_kvk_þgf", "Breyttu tveim tommum í metra"],
                [2, "ft_kvk_þgf", "Breyttu tveim tommum í kílómetra"],
            ],
        ),
        (
            [3, "ft_kk_þgf", "þremur"],
            [
                [3, "ft_kk_þgf", "Hversu mörg fet eru í þremur millimetrum?"],
                [3, "ft_kk_þgf", "Hversu margar tommur eru í þremur millimetrum?"],
                [3, "ft_kk_þgf", "Hversu margar mílur eru í þremur millimetrum?"],
                [3, "ft_kk_þgf", "Hversu margir sentimetrar eru í þremur millimetrum?"],
                [3, "ft_kk_þgf", "Hversu margir metrar eru í þremur millimetrum?"],
                [3, "ft_kk_þgf", "Hversu margir kílómetrar eru í þremur millimetrum?"],
                [3, "ft_kk_þgf", "Hversu mörg fet eru í þremur sentimetrum?"],
                [3, "ft_kk_þgf", "Hversu margar tommur eru í þremur sentimetrum?"],
                [3, "ft_kk_þgf", "Hversu margar mílur eru í þremur sentimetrum?"],
                [3, "ft_kk_þgf", "Hversu margir millimetrar eru í þremur sentimetrum?"],
                [3, "ft_kk_þgf", "Hversu margir metrar eru í þremur sentimetrum?"],
                [3, "ft_kk_þgf", "Hversu margir kílómetrar eru í þremur sentimetrum?"],
                [3, "ft_kk_þgf", "Hversu mörg fet eru í þremur metrum?"],
                [3, "ft_kk_þgf", "Hversu margar tommur eru í þremur metrum?"],
                [3, "ft_kk_þgf", "Hversu margar mílur eru í þremur metrum?"],
                [3, "ft_kk_þgf", "Hversu margir millimetrar eru í þremur metrum?"],
                [3, "ft_kk_þgf", "Hversu margir sentimetrar eru í þremur metrum?"],
                [3, "ft_kk_þgf", "Hversu margir kílómetrar eru í þremur metrum?"],
                [3, "ft_kk_þgf", "Hversu mörg fet eru í þremur kílómetrum?"],
                [3, "ft_kk_þgf", "Hversu margar tommur eru í þremur kílómetrum?"],
                [3, "ft_kk_þgf", "Hversu margar mílur eru í þremur kílómetrum?"],
                [3, "ft_kk_þgf", "Hversu margir millimetrar eru í þremur kílómetrum?"],
                [3, "ft_kk_þgf", "Hversu margir sentimetrar eru í þremur kílómetrum?"],
                [3, "ft_kk_þgf", "Hversu margir metrar eru í þremur kílómetrum?"],
                [3, "ft_kk_þgf", "Breyttu þremur millimetrum í fet"],
                [3, "ft_kk_þgf", "Breyttu þremur millimetrum í tommur"],
                [3, "ft_kk_þgf", "Breyttu þremur millimetrum í mílur"],
                [3, "ft_kk_þgf", "Breyttu þremur millimetrum í sentimetra"],
                [3, "ft_kk_þgf", "Breyttu þremur millimetrum í metra"],
                [3, "ft_kk_þgf", "Breyttu þremur millimetrum í kílómetra"],
                [3, "ft_kk_þgf", "Breyttu þremur sentimetrum í fet"],
                [3, "ft_kk_þgf", "Breyttu þremur sentimetrum í tommur"],
                [3, "ft_kk_þgf", "Breyttu þremur sentimetrum í mílur"],
                [3, "ft_kk_þgf", "Breyttu þremur sentimetrum í millimetra"],
                [3, "ft_kk_þgf", "Breyttu þremur sentimetrum í metra"],
                [3, "ft_kk_þgf", "Breyttu þremur sentimetrum í kílómetra"],
                [3, "ft_kk_þgf", "Breyttu þremur metrum í fet"],
                [3, "ft_kk_þgf", "Breyttu þremur metrum í tommur"],
                [3, "ft_kk_þgf", "Breyttu þremur metrum í mílur"],
                [3, "ft_kk_þgf", "Breyttu þremur metrum í millimetra"],
                [3, "ft_kk_þgf", "Breyttu þremur metrum í sentimetra"],
                [3, "ft_kk_þgf", "Breyttu þremur metrum í kílómetra"],
                [3, "ft_kk_þgf", "Breyttu þremur kílómetrum í fet"],
                [3, "ft_kk_þgf", "Breyttu þremur kílómetrum í tommur"],
                [3, "ft_kk_þgf", "Breyttu þremur kílómetrum í mílur"],
                [3, "ft_kk_þgf", "Breyttu þremur kílómetrum í millimetra"],
                [3, "ft_kk_þgf", "Breyttu þremur kílómetrum í sentimetra"],
                [3, "ft_kk_þgf", "Breyttu þremur kílómetrum í metra"],
            ],
        ),
        (
            [5, "at_af", "fimm"],
            [
                [5, "at_af", "Hvað eru fimm millimetrar mörg fet?"],
                [5, "at_af", "Hvað eru fimm millimetrar margar tommur?"],
                [5, "at_af", "Hvað eru fimm millimetrar margar mílur?"],
                [5, "at_af", "Hvað eru fimm millimetrar margir sentimetrar?"],
                [5, "at_af", "Hvað eru fimm millimetrar margir metrar?"],
                [5, "at_af", "Hvað eru fimm millimetrar margir kílómetrar?"],
                [5, "at_af", "Hvað eru fimm sentimetrar mörg fet?"],
                [5, "at_af", "Hvað eru fimm sentimetrar margar tommur?"],
                [5, "at_af", "Hvað eru fimm sentimetrar margar mílur?"],
                [5, "at_af", "Hvað eru fimm sentimetrar margir millimetrar?"],
                [5, "at_af", "Hvað eru fimm sentimetrar margir metrar?"],
                [5, "at_af", "Hvað eru fimm sentimetrar margir kílómetrar?"],
                [5, "at_af", "Hvað eru fimm metrar mörg fet?"],
                [5, "at_af", "Hvað eru fimm metrar margar tommur?"],
                [5, "at_af", "Hvað eru fimm metrar margar mílur?"],
                [5, "at_af", "Hvað eru fimm metrar margir millimetrar?"],
                [5, "at_af", "Hvað eru fimm metrar margir sentimetrar?"],
                [5, "at_af", "Hvað eru fimm metrar margir kílómetrar?"],
                [5, "at_af", "Hvað eru fimm kílómetrar mörg fet?"],
                [5, "at_af", "Hvað eru fimm kílómetrar margar tommur?"],
                [5, "at_af", "Hvað eru fimm kílómetrar margar mílur?"],
                [5, "at_af", "Hvað eru fimm kílómetrar margir millimetrar?"],
                [5, "at_af", "Hvað eru fimm kílómetrar margir sentimetrar?"],
                [5, "at_af", "Hvað eru fimm kílómetrar margir metrar?"],
                [5, "at_af", "Hvað eru fimm mílur mörg fet?"],
                [5, "at_af", "Hvað eru fimm mílur margar tommur?"],
                [5, "at_af", "Hvað eru fimm mílur margir millimetrar?"],
                [5, "at_af", "Hvað eru fimm mílur margir sentimetrar?"],
                [5, "at_af", "Hvað eru fimm mílur margir metrar?"],
                [5, "at_af", "Hvað eru fimm mílur margir kílómetrar?"],
                [5, "at_af", "Hvað eru fimm tommur mörg fet?"],
                [5, "at_af", "Hvað eru fimm tommur margar mílur?"],
                [5, "at_af", "Hvað eru fimm tommur margir millimetrar?"],
                [5, "at_af", "Hvað eru fimm tommur margir sentimetrar?"],
                [5, "at_af", "Hvað eru fimm tommur margir metrar?"],
                [5, "at_af", "Hvað eru fimm tommur margir kílómetrar?"],
                [5, "at_af", "Hvað eru fimm fet margar tommur?"],
                [5, "at_af", "Hvað eru fimm fet margar mílur?"],
                [5, "at_af", "Hvað eru fimm fet margir millimetrar?"],
                [5, "at_af", "Hvað eru fimm fet margir sentimetrar?"],
                [5, "at_af", "Hvað eru fimm fet margir metrar?"],
                [5, "at_af", "Hvað eru fimm fet margir kílómetrar?"],
                [5, "at_af", "Hversu mörg fet eru í fimm millimetrum?"],
                [5, "at_af", "Hversu margar tommur eru í fimm millimetrum?"],
                [5, "at_af", "Hversu margar mílur eru í fimm millimetrum?"],
                [5, "at_af", "Hversu margir sentimetrar eru í fimm millimetrum?"],
                [5, "at_af", "Hversu margir metrar eru í fimm millimetrum?"],
                [5, "at_af", "Hversu margir kílómetrar eru í fimm millimetrum?"],
                [5, "at_af", "Hversu mörg fet eru í fimm sentimetrum?"],
                [5, "at_af", "Hversu margar tommur eru í fimm sentimetrum?"],
                [5, "at_af", "Hversu margar mílur eru í fimm sentimetrum?"],
                [5, "at_af", "Hversu margir millimetrar eru í fimm sentimetrum?"],
                [5, "at_af", "Hversu margir metrar eru í fimm sentimetrum?"],
                [5, "at_af", "Hversu margir kílómetrar eru í fimm sentimetrum?"],
                [5, "at_af", "Hversu mörg fet eru í fimm metrum?"],
                [5, "at_af", "Hversu margar tommur eru í fimm metrum?"],
                [5, "at_af", "Hversu margar mílur eru í fimm metrum?"],
                [5, "at_af", "Hversu margir millimetrar eru í fimm metrum?"],
                [5, "at_af", "Hversu margir sentimetrar eru í fimm metrum?"],
                [5, "at_af", "Hversu margir kílómetrar eru í fimm metrum?"],
                [5, "at_af", "Hversu mörg fet eru í fimm kílómetrum?"],
                [5, "at_af", "Hversu margar tommur eru í fimm kílómetrum?"],
                [5, "at_af", "Hversu margar mílur eru í fimm kílómetrum?"],
                [5, "at_af", "Hversu margir millimetrar eru í fimm kílómetrum?"],
                [5, "at_af", "Hversu margir sentimetrar eru í fimm kílómetrum?"],
                [5, "at_af", "Hversu margir metrar eru í fimm kílómetrum?"],
                [5, "at_af", "Hversu mörg fet eru í fimm mílum?"],
                [5, "at_af", "Hversu margar tommur eru í fimm mílum?"],
                [5, "at_af", "Hversu margir millimetrar eru í fimm mílum?"],
                [5, "at_af", "Hversu margir sentimetrar eru í fimm mílum?"],
                [5, "at_af", "Hversu margir metrar eru í fimm mílum?"],
                [5, "at_af", "Hversu margir kílómetrar eru í fimm mílum?"],
                [5, "at_af", "Hversu mörg fet eru í fimm tommum?"],
                [5, "at_af", "Hversu margar mílur eru í fimm tommum?"],
                [5, "at_af", "Hversu margir millimetrar eru í fimm tommum?"],
                [5, "at_af", "Hversu margir sentimetrar eru í fimm tommum?"],
                [5, "at_af", "Hversu margir metrar eru í fimm tommum?"],
                [5, "at_af", "Hversu margir kílómetrar eru í fimm tommum?"],
                [5, "at_af", "Hversu margar tommur eru í fimm fetum?"],
                [5, "at_af", "Hversu margar mílur eru í fimm fetum?"],
                [5, "at_af", "Hversu margir millimetrar eru í fimm fetum?"],
                [5, "at_af", "Hversu margir sentimetrar eru í fimm fetum?"],
                [5, "at_af", "Hversu margir metrar eru í fimm fetum?"],
                [5, "at_af", "Hversu margir kílómetrar eru í fimm fetum?"],
                [5, "at_af", "Breyttu fimm millimetrum í fet"],
                [5, "at_af", "Breyttu fimm millimetrum í tommur"],
                [5, "at_af", "Breyttu fimm millimetrum í mílur"],
                [5, "at_af", "Breyttu fimm millimetrum í sentimetra"],
                [5, "at_af", "Breyttu fimm millimetrum í metra"],
                [5, "at_af", "Breyttu fimm millimetrum í kílómetra"],
                [5, "at_af", "Breyttu fimm sentimetrum í fet"],
                [5, "at_af", "Breyttu fimm sentimetrum í tommur"],
                [5, "at_af", "Breyttu fimm sentimetrum í mílur"],
                [5, "at_af", "Breyttu fimm sentimetrum í millimetra"],
                [5, "at_af", "Breyttu fimm sentimetrum í metra"],
                [5, "at_af", "Breyttu fimm sentimetrum í kílómetra"],
                [5, "at_af", "Breyttu fimm metrum í fet"],
                [5, "at_af", "Breyttu fimm metrum í tommur"],
                [5, "at_af", "Breyttu fimm metrum í mílur"],
                [5, "at_af", "Breyttu fimm metrum í millimetra"],
                [5, "at_af", "Breyttu fimm metrum í sentimetra"],
                [5, "at_af", "Breyttu fimm metrum í kílómetra"],
                [5, "at_af", "Breyttu fimm kílómetrum í fet"],
                [5, "at_af", "Breyttu fimm kílómetrum í tommur"],
                [5, "at_af", "Breyttu fimm kílómetrum í mílur"],
                [5, "at_af", "Breyttu fimm kílómetrum í millimetra"],
                [5, "at_af", "Breyttu fimm kílómetrum í sentimetra"],
                [5, "at_af", "Breyttu fimm kílómetrum í metra"],
                [5, "at_af", "Breyttu fimm mílum í fet"],
                [5, "at_af", "Breyttu fimm mílum í tommur"],
                [5, "at_af", "Breyttu fimm mílum í millimetra"],
                [5, "at_af", "Breyttu fimm mílum í sentimetra"],
                [5, "at_af", "Breyttu fimm mílum í metra"],
                [5, "at_af", "Breyttu fimm mílum í kílómetra"],
                [5, "at_af", "Breyttu fimm tommum í fet"],
                [5, "at_af", "Breyttu fimm tommum í mílur"],
                [5, "at_af", "Breyttu fimm tommum í millimetra"],
                [5, "at_af", "Breyttu fimm tommum í sentimetra"],
                [5, "at_af", "Breyttu fimm tommum í metra"],
                [5, "at_af", "Breyttu fimm tommum í kílómetra"],
                [5, "at_af", "Breyttu fimm fetum í tommur"],
                [5, "at_af", "Breyttu fimm fetum í mílur"],
                [5, "at_af", "Breyttu fimm fetum í millimetra"],
                [5, "at_af", "Breyttu fimm fetum í sentimetra"],
                [5, "at_af", "Breyttu fimm fetum í metra"],
                [5, "at_af", "Breyttu fimm fetum í kílómetra"],
                [5, "at_af", "Hvað eru fimm lítrar margir millilítrar?"],
                [5, "at_af", "Hvað eru fimm lítrar margir desilítrar?"],
                [5, "at_af", "Hvað eru fimm lítrar mörg grömm?"],
                [5, "at_af", "Hvað eru fimm lítrar mörg kílógrömm?"],
                [5, "at_af", "Hvað eru fimm lítrar mörg pund?"],
                [5, "at_af", "Hvað eru fimm lítrar margir bollar?"],
                [5, "at_af", "Hvað eru fimm lítrar margar únsur?"],
                [5, "at_af", "Hvað eru fimm lítrar margar matskeiðar?"],
                [5, "at_af", "Hvað eru fimm lítrar margir pelar?"],
                [5, "at_af", "Hvað eru fimm desilítrar margir lítrar?"],
                [5, "at_af", "Hvað eru fimm desilítrar margir millilítrar?"],
                [5, "at_af", "Hvað eru fimm desilítrar mörg grömm?"],
                [5, "at_af", "Hvað eru fimm desilítrar mörg kílógrömm?"],
                [5, "at_af", "Hvað eru fimm desilítrar mörg pund?"],
                [5, "at_af", "Hvað eru fimm desilítrar margir bollar?"],
                [5, "at_af", "Hvað eru fimm desilítrar margar únsur?"],
                [5, "at_af", "Hvað eru fimm desilítrar margar matskeiðar?"],
                [5, "at_af", "Hvað eru fimm desilítrar margir pelar?"],
                [5, "at_af", "Hvað eru fimm millilítrar margir lítrar?"],
                [5, "at_af", "Hvað eru fimm millilítrar margir desilítrar?"],
                [5, "at_af", "Hvað eru fimm millilítrar mörg grömm?"],
                [5, "at_af", "Hvað eru fimm millilítrar mörg kílógrömm?"],
                [5, "at_af", "Hvað eru fimm millilítrar mörg pund?"],
                [5, "at_af", "Hvað eru fimm millilítrar margir bollar?"],
                [5, "at_af", "Hvað eru fimm millilítrar margar únsur?"],
                [5, "at_af", "Hvað eru fimm millilítrar margar matskeiðar?"],
                [5, "at_af", "Hvað eru fimm millilítrar margir pelar?"],
                [5, "at_af", "Hvað eru fimm grömm margir lítrar?"],
                [5, "at_af", "Hvað eru fimm grömm margir millilítrar?"],
                [5, "at_af", "Hvað eru fimm grömm margir desilítrar?"],
                [5, "at_af", "Hvað eru fimm grömm mörg kílógrömm?"],
                [5, "at_af", "Hvað eru fimm grömm mörg pund?"],
                [5, "at_af", "Hvað eru fimm grömm margir bollar?"],
                [5, "at_af", "Hvað eru fimm grömm margar únsur?"],
                [5, "at_af", "Hvað eru fimm grömm margar matskeiðar?"],
                [5, "at_af", "Hvað eru fimm grömm margir pelar?"],
            ],
        ),
    ],
)
def test_integers(test_input, expected):
    assert generate_sentances_integers(*test_input) == expected
